apiVersion: v1
data:
  APP_FOLDER: /usr/src/app
  FLASK_APP: project/__init__.py
  FLASK_ENV: development
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-env-dev
  name: env-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: propensity-to-sell-nginx
  name: propensity-to-sell-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: propensity-to-sell-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: propensity-to-sell-nginx
    spec:
      containers:
        - name: propensity-to-sell-model
          args:
            - gunicorn
            - --bind
            - 0.0.0.0:5000
            - manage:app
          env:
            - name: APP_FOLDER
              valueFrom:
                configMapKeyRef:
                  key: APP_FOLDER
                  name: env-dev
            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  key: FLASK_APP
                  name: env-dev
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  key: FLASK_ENV
                  name: env-dev
          image: propentity-to-sell-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
        - name: propentity-to-sell-proxy
          image: propentity-to-sell-proxy:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: propensity-to-sell-nginx
spec:
  type: LoadBalancer
  ports:
    - name: "1337"
      port: 1337
      targetPort: 80
  selector:
    app: propensity-to-sell-nginx