apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: propensity-to-sell-model
  name: propensity-to-sell-model
spec:
  replicas: 3
  selector:
    matchLabels:
      app: propensity-to-sell-model
  strategy: {}
  template:
    metadata:
      labels:
        app: propensity-to-sell-model
    spec:
      containers:
        - args:
            - gunicorn
            - --bind
            - 0.0.0.0:5000
            - manage:app
          env:
            - name: APP_FOLDER
              valueFrom:
                configMapKeyRef:
                  key: APP_FOLDER
                  name: env-dev
            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  key: FLASK_APP
                  name: env-dev
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  key: FLASK_ENV
                  name: env-dev
          image: propentity-to-sell-service:latest
          terminationMessagePath: "/tmp/my-log"
          imagePullPolicy: Never
          name: propensity-to-sell-service
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
